- hosts: wp_nodes
  become: yes
  vars: 
    DB_NAME: blog
    DB_USER: blog
    DB_PW: blog!
  tasks:
    - name: "install http server"
      yum:
        name: httpd
        state: present
    - name: "install EPEL"
      yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        state: present
    - name: "install php repo"
      yum:
        name: https://rpms.remirepo.net/enterprise/remi-release-7.rpm
        state: present
    - name: "install php packages"
      yum:
        name: php80-php, php80, php80-php-mysqlnd, php80-php-pecl-mysql
        state: present
    - name: "copy mariadb repo cfg"
      copy:
        src: files/Mariadb.repo
        dest: /etc/yum.repos.d/Mariadb.repo
    - name: "install mariadb"
      yum:
        name: MariaDB-server, MariaDB-client
        state: present
    - name: "reload mariadb"
      systemd:
        name: mariadb
        state: started
    - name: "install mysql related module"
      yum:
        name: MySQL-python
        state: present
    - name: "create wp's db"
      mysql_db:
        name: "{{DB_NAME}}"
        state: present
    - name: "create user && asign privileges"
      mysql_user:
        name: "{{DB_USER}}"
        password: "{{DB_PW}}"
        priv: "{{DB_NAME}}.*:ALL"
        state: present
    - name: "download wordpress && extract wp"
      unarchive:
        src: https://pl.wordpress.org/latest-pl_PL.tar.gz
        dest: /var/www
        remote_src: yes
    - name: "copy vhost cfg"
      copy:
        src: files/blog-vhost.conf
        dest: /etc/httpd/conf.d/blog.conf
    - name: "copy wp cfg"
      template:
        src: files/wp-config.php
        dest: /var/www/wordpress/wp-config.php 
    - name: "reload apache"
      systemd:
        name: httpd
        state: reloaded